In [1]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/ralbu85/DataScience_2022S/master/data/datacleaning.csv")
df

    Duration  Pulse  Maxpulse  Calories
0         60  117.0       145     479.0
1         60  103.0       135     340.0
2         45  109.0       175     282.4
3         45    NaN       148     406.0
4         60  100.0       120     250.7
5        450  104.0       134     253.3
6         30  109.0       133     195.1
7         60    NaN       124     269.0
8         60  103.0       147     329.3
9         60  100.0       120     250.7
10        60  100.0       120     250.7
11        60   98.0       120     215.2
12        45   90.0       112       NaN
13        60  103.0       123     323.0
14        60  100.0       120     250.7
15        45    NaN       132     246.0
16        60  102.0       126     334.5
17        60  100.0       120     250.0
18        60  103.0       132       NaN

In [2]:
df.isnull().sum()

Duration    0
Pulse       3
Maxpulse    0
Calories    2
dtype: int64

In [3]:
df2 = df.dropna(axis=0) #df 자체 값이 바뀌는 것은 아님
# 비어있는 NaN, axis=0이면 행 삭제, axis =1 이면 열 삭제
df2 # = 을 통해 값이 바뀜

    Duration  Pulse  Maxpulse  Calories
0         60  117.0       145     479.0
1         60  103.0       135     340.0
2         45  109.0       175     282.4
4         60  100.0       120     250.7
5        450  104.0       134     253.3
6         30  109.0       133     195.1
8         60  103.0       147     329.3
9         60  100.0       120     250.7
10        60  100.0       120     250.7
11        60   98.0       120     215.2
13        60  103.0       123     323.0
14        60  100.0       120     250.7
16        60  102.0       126     334.5
17        60  100.0       120     250.0

In [4]:
df3 = df.dropna(axis = 1)
df3

    Duration  Maxpulse
0         60       145
1         60       135
2         45       175
3         45       148
4         60       120
5        450       134
6         30       133
7         60       124
8         60       147
9         60       120
10        60       120
11        60       120
12        45       112
13        60       123
14        60       120
15        45       132
16        60       126
17        60       120
18        60       132

In [5]:
df4 = df.fillna(100)
df4

    Duration  Pulse  Maxpulse  Calories
0         60  117.0       145     479.0
1         60  103.0       135     340.0
2         45  109.0       175     282.4
3         45  100.0       148     406.0
4         60  100.0       120     250.7
5        450  104.0       134     253.3
6         30  109.0       133     195.1
7         60  100.0       124     269.0
8         60  103.0       147     329.3
9         60  100.0       120     250.7
10        60  100.0       120     250.7
11        60   98.0       120     215.2
12        45   90.0       112     100.0
13        60  103.0       123     323.0
14        60  100.0       120     250.7
15        45  100.0       132     246.0
16        60  102.0       126     334.5
17        60  100.0       120     250.0
18        60  103.0       132     100.0

In [6]:
df['Pulse'] = df['Pulse'].fillna(130)
df

    Duration  Pulse  Maxpulse  Calories
0         60  117.0       145     479.0
1         60  103.0       135     340.0
2         45  109.0       175     282.4
3         45  130.0       148     406.0
4         60  100.0       120     250.7
5        450  104.0       134     253.3
6         30  109.0       133     195.1
7         60  130.0       124     269.0
8         60  103.0       147     329.3
9         60  100.0       120     250.7
10        60  100.0       120     250.7
11        60   98.0       120     215.2
12        45   90.0       112       NaN
13        60  103.0       123     323.0
14        60  100.0       120     250.7
15        45  130.0       132     246.0
16        60  102.0       126     334.5
17        60  100.0       120     250.0
18        60  103.0       132       NaN

In [7]:
df['Calories'] = df['Calories'].fillna(11)
df

    Duration  Pulse  Maxpulse  Calories
0         60  117.0       145     479.0
1         60  103.0       135     340.0
2         45  109.0       175     282.4
3         45  130.0       148     406.0
4         60  100.0       120     250.7
5        450  104.0       134     253.3
6         30  109.0       133     195.1
7         60  130.0       124     269.0
8         60  103.0       147     329.3
9         60  100.0       120     250.7
10        60  100.0       120     250.7
11        60   98.0       120     215.2
12        45   90.0       112      11.0
13        60  103.0       123     323.0
14        60  100.0       120     250.7
15        45  130.0       132     246.0
16        60  102.0       126     334.5
17        60  100.0       120     250.0
18        60  103.0       132      11.0

In [8]:
df = pd.read_csv("https://raw.githubusercontent.com/ralbu85/DataScience_2022S/master/data/datacleaning.csv")
df

    Duration  Pulse  Maxpulse  Calories
0         60  117.0       145     479.0
1         60  103.0       135     340.0
2         45  109.0       175     282.4
3         45    NaN       148     406.0
4         60  100.0       120     250.7
5        450  104.0       134     253.3
6         30  109.0       133     195.1
7         60    NaN       124     269.0
8         60  103.0       147     329.3
9         60  100.0       120     250.7
10        60  100.0       120     250.7
11        60   98.0       120     215.2
12        45   90.0       112       NaN
13        60  103.0       123     323.0
14        60  100.0       120     250.7
15        45    NaN       132     246.0
16        60  102.0       126     334.5
17        60  100.0       120     250.0
18        60  103.0       132       NaN

In [9]:
df['Pulse'] =df['Pulse'].fillna(df['Pulse'].mean())
df['Calories'] = df['Calories'].fillna(df['Calories'].mean())

In [10]:
df

    Duration     Pulse  Maxpulse    Calories
0         60  117.0000       145  479.000000
1         60  103.0000       135  340.000000
2         45  109.0000       175  282.400000
3         45  102.5625       148  406.000000
4         60  100.0000       120  250.700000
5        450  104.0000       134  253.300000
6         30  109.0000       133  195.100000
7         60  102.5625       124  269.000000
8         60  103.0000       147  329.300000
9         60  100.0000       120  250.700000
10        60  100.0000       120  250.700000
11        60   98.0000       120  215.200000
12        45   90.0000       112  289.741176
13        60  103.0000       123  323.000000
14        60  100.0000       120  250.700000
15        45  102.5625       132  246.000000
16        60  102.0000       126  334.500000
17        60  100.0000       120  250.000000
18        60  103.0000       132  289.741176

In [11]:
df.fillna(df.mean()) #한번에 빈칸 평균값 넣어서 채워줌

    Duration     Pulse  Maxpulse    Calories
0         60  117.0000       145  479.000000
1         60  103.0000       135  340.000000
2         45  109.0000       175  282.400000
3         45  102.5625       148  406.000000
4         60  100.0000       120  250.700000
5        450  104.0000       134  253.300000
6         30  109.0000       133  195.100000
7         60  102.5625       124  269.000000
8         60  103.0000       147  329.300000
9         60  100.0000       120  250.700000
10        60  100.0000       120  250.700000
11        60   98.0000       120  215.200000
12        45   90.0000       112  289.741176
13        60  103.0000       123  323.000000
14        60  100.0000       120  250.700000
15        45  102.5625       132  246.000000
16        60  102.0000       126  334.500000
17        60  100.0000       120  250.000000
18        60  103.0000       132  289.741176

In [12]:
df.median()

Duration     60.0000
Pulse       102.5625
Maxpulse    126.0000
Calories    269.0000
dtype: float64

In [13]:
df.drop_duplicates() #중복 제거, 모든 행이 같아야 지워짐

    Duration     Pulse  Maxpulse    Calories
0         60  117.0000       145  479.000000
1         60  103.0000       135  340.000000
2         45  109.0000       175  282.400000
3         45  102.5625       148  406.000000
4         60  100.0000       120  250.700000
5        450  104.0000       134  253.300000
6         30  109.0000       133  195.100000
7         60  102.5625       124  269.000000
8         60  103.0000       147  329.300000
11        60   98.0000       120  215.200000
12        45   90.0000       112  289.741176
13        60  103.0000       123  323.000000
15        45  102.5625       132  246.000000
16        60  102.0000       126  334.500000
17        60  100.0000       120  250.000000
18        60  103.0000       132  289.741176

In [14]:
df.drop_duplicates(keep = 'last') #마지막 것만 남기고 제거 ex)14번

    Duration     Pulse  Maxpulse    Calories
0         60  117.0000       145  479.000000
1         60  103.0000       135  340.000000
2         45  109.0000       175  282.400000
3         45  102.5625       148  406.000000
5        450  104.0000       134  253.300000
6         30  109.0000       133  195.100000
7         60  102.5625       124  269.000000
8         60  103.0000       147  329.300000
11        60   98.0000       120  215.200000
12        45   90.0000       112  289.741176
13        60  103.0000       123  323.000000
14        60  100.0000       120  250.700000
15        45  102.5625       132  246.000000
16        60  102.0000       126  334.500000
17        60  100.0000       120  250.000000
18        60  103.0000       132  289.741176